### PR TITLE
Several updates to the server.md file & added Gitter badge.

### PR DESCRIPTION
**Pull request by bnb**
I updated the server.md file to have more information about running a Connect server. Also added a Gitter badge to the README.md. Apologies for not making these two separate requests.

### CODE REVIEW

**Comment by christiansmith** [comment]
Great updates. Thanks!

**Comment by bnb** [comment]
@christiansmith If you could go through the HTML comments I left (`ctrl` + `f` -> `<!--`), I'd like to get filled in on that information, if possible.

**Comment by christiansmith** [comment]
> Is $_ a real command? 99.99% sure it won't work on Windows.

Yes. It's a [real command](http://www.thegeekstuff.com/2010/05/bash-shell-special-parameters/), and yes you're probably right about Windows. Feel free to change the instructions to be easier to follow.

> This will generate a file tree that looks something like this: >

How about: "This will generate a file tree that looks similar to the following example:"

> Why is it beneficial to use Connect-generated keys?

I guess because it's a pain in the ass if you don't know what you're doing to look up the commands, generate the files, and copy them in place. It can be reworded.

> **Use:** signing cookies  

Good question. Need to review this code and see what exactly it's doing vs the `session_secret`

> **Type:** string - options: `realm` >

This could be any scope the Connect operator registers with the server. It's up them to decide which scope they want, if any.

**Comment by bnb** [comment]
> >This will generate a file tree that looks something like this: >

> How about: "This will generate a file tree that looks similar to the following example:"

I think it needs to be explicit - since this is a generator, its output should be known. If there are settings/variables/whatever that would result in a different structure, those should be explained. I can do most of the writing if you can give me a simple breakdown of the reasons (even in just a bulleted list) it would be different than the example.

> > Type: string - options: realm >

> This could be any scope the Connect operator registers with the server. It's up them to decide which scope they want, if any.

With the Connect server or the 3rd party's authentication server? If with the Connect server, are they deciding from a set of specifically named scopes that they can choose from?

**Comment by christiansmith** [comment]
Here's the output of `nv init`:

```bash
$ nv init

Initializing Anvil Connect deployment repository:

* Initialized git repository
* Generated package.json
* Generated bower.json
* Generated config/development.json
* Generated config/production.json
* Generated server.js
* Generated views
* Generated public/images
* Generated public/javascript
* Generated public/stylesheets
* Generated .bowerrc
* Generated .gitignore
* Generated .modulusignore
* Generated Dockerfile
* Generated docker-compose.yml
* Generated nginx.conf
* Generated RSA keypair

Your Anvil Connect deployment repository is initialized. Next steps:

1. Install npm dependencies if you plan to run the server locally.

      $ npm install
      $ bower install

2. Adjust your configuration files as needed, then be sure to initialize
   your development and production databases.

      // development
      $ nv migrate

      // production
      $ NODE_ENV=production nv migrate

3. Run Anvil Connect in development mode

      // with npm script
      $ npm start

      // or directly with node
      $ node server.js

4. Customize the interface by editing /views and adding static assets to /public.

5. Remember to commit your changes.

      $ git commit -m 'My custom authorization server'


You can safely rerun this command without overwriting existing files.
```


Scope:

It's the set of scopes that the operator of Connect has defined for their own auth server, as opposed to Google APIs scopes, for example.

**Pull request merged**
